#!/bin/bash
set -ex


if [ -b "$1" ]; then
  echo "Testing if $1 is empty"

    if od -A d -N 1048576 $1 | head -n 3 | diff /assets/od-1m0 - >/dev/null 2>&1; then
      echo "Auto-format Device $1"
      mkfs.ext4 $1
    fi

fi
