#!/bin/bash
set -e

AWS_REGION=$(ec2-metadata-value --availability-zone | sed 's/.$//')
DEFAULT_STORAGE_DRIVER="convoy-ebs"

CONVOY_SOCK="${CONVOY_SOCK:-/host/var/run/convoy/convoy-ebs.sock}"
STORAGE_DRIVER="${STORAGE_DRIVER:-$DEFAULT_STORAGE_DRIVER}"
VOLUME_NAME="${VOLUME_NAME:-$VOLUME_ID}"

if [ -n "$GREEDY" ]; then
  convoy -s $CONVOY_SOCK \
    delete \
    -r \
    $VOLUME_NAME || true

  aws ec2 detach-volume --volume-id $VOLUME_ID --region $AWS_REGION || true

  aws ec2 wait volume-available --volume-ids $VOLUME_ID
fi

echo "VOLUME_NAME=$VOLUME_NAME"
echo "VOLUME_ID=$VOLUME_ID"

CREATE_OUTPUT=$(convoy -s $CONVOY_SOCK \
  --verbose \
  create \
  --id=$VOLUME_ID \
  $VOLUME_NAME)

DEVICE=$(echo $CREATE_OUTPUT | grep -oP "(?<=Device\":\s\")[^\"]+")

echo $DEVICE

/scripts/auto-format $DEVICE

